#
# .gitea/gitea-ci.yaml
#
name: Build And Test
run-name: ${{ gitea.actor }} is runs ci pipeline
#on: [ push ]
on:
  push:
    branches:
      - main   
    paths-ignore:
      - LICENCE
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - LICENCE
      - 'docs/**'

jobs:
  Gitea-Terraform-Build-Deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Terraform & Terragrunt
        run: | 
          curl -L curl -sfL https://direnv.net/install.sh | bash
          echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
          curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash && tfswitch 0.14.7
          curl -L https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh | bash && tgswitch 0.28.7
      - name: Run Terraform
        run: |
          source ~/.bashrc
          direnv allow
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          tfswitch 1.0.11
          tgswitch 0.35.10
          cd apne2/sqs
          terragrunt plan
          terragrunt apply -auto-approve