version: "3"

services:
  act_runner:
    image: gitea/act_runner:0.2.10
    container_name: act_runner
    privileged: true
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "https://localhost:3300"
      GITEA_RUNNER_REGISTRATION_TOKEN: rDEwDjXQKwZs4Kr0DqQ7GOzpzgs8QvCTwZn4m9ff
      GITEA_RUNNER_NAME: "act_runner"
      #GITEA_RUNNER_LABELS: ubuntu-latest:docker
    volumes:
      #- ~/gitea/act-runner/data:/data
      #- ~/gitea/act-runner/cache:/root/.cache    
      - ./config.yaml:/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock